version: 2
updates:
  - package-ecosystem: maven
    directory: /connectors/wikimedia
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /connectors/eonet
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /connectors/slnews
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /flink-jobs
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
