apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: slnews-source
  namespace: vega
  labels:
    strimzi.io/cluster: vega-kafka-connect
spec:
  class: io.vega.connector.slnews.SLNewsSourceConnector
  tasksMax: 1
  config:
    topic: raw-sl-news
  state: running
