apiVersion: v1
kind: ConfigMap
metadata:
  name: vega-kafka-topics
  namespace: vega
data:
  raw-wiki-events.yaml: |
    partitions: 6
    replicas: 3
    config:
      retention.ms: "604800000"
  raw-natural-events.yaml: |
    partitions: 3
    replicas: 3
  raw-sl-news.yaml: |
    partitions: 3
    replicas: 3
  vega-dead-letter.yaml: |
    partitions: 1
    replicas: 3
