apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: wikimedia-source
  namespace: vega
  labels:
    strimzi.io/cluster: vega-kafka-connect
spec:
  class: io.vega.connector.wikimedia.WikimediaSourceConnector
  tasksMax: 1
  config:
    topic: raw-wiki-events
  state: running
